import type { RouteObject } from "react-router-dom"

import { NotFoundPage } from "@app/features/core/components/pages/NotFoundPage"
import {
    AnimateMotionPage,
    AnimatePage,
    AnimateTransformPage,
    CirclePage,
    ClipPathPage,
    EllipsePage,
    ForeignObjectPage,
    LinearGradientPage,
    LinePage,
    MarkerPage,
    MaskPage,
    MPathPage,
    PathPage,
    PolygonPage,
    PolylinePage,
    RadialGradientPage,
    RectPage,
    StopPage,
    SvgPage,
    SymbolPage,
    TextPage,
    TextPathPage,
    TSpanPage,
    UsePage,
} from "./components"

export const basePackageRoutes: RouteObject = {
    path: "components",
    children: [
        { index: true,              element: <NotFoundPage />         },
        { path: "Animate",          element: <AnimatePage />          },
        { path: "AnimateMotion",    element: <AnimateMotionPage />    },
        { path: "AnimateTransform", element: <AnimateTransformPage /> },
        { path: "Circle",           element: <CirclePage />           },
        { path: "ClipPath",         element: <ClipPathPage />         },
        { path: "Ellipse",          element: <EllipsePage />          },
        { path: "ForeignObject",    element: <ForeignObjectPage />    },
        { path: "Line",             element: <LinePage />             },
        { path: "LinearGradient",   element: <LinearGradientPage />   },
        { path: "Mask",             element: <MaskPage />             },
        { path: "Marker",           element: <MarkerPage />           },
        { path: "MPath",            element: <MPathPage />            },
        { path: "Path",             element: <PathPage />             },
        { path: "Polygon",          element: <PolygonPage />          },
        { path: "Polyline",         element: <PolylinePage />         },
        { path: "RadialGradient",   element: <RadialGradientPage />   },
        { path: "Rect",             element: <RectPage />             },
        { path: "Stop",             element: <StopPage />             },
        { path: "Svg",              element: <SvgPage />              },
        { path: "Symbol",           element: <SymbolPage />           },
        { path: "Text",             element: <TextPage />             },
        { path: "TextPath",         element: <TextPathPage />         },
        { path: "TSpan",            element: <TSpanPage />            },
        { path: "Use",              element: <UsePage />              },
    ],
}

export const basePackageSideNavItems: ILinkData[] = [
    { title: "Animate",          to: "/components/Animate" },
    { title: "AnimateMotion",    to: "/components/AnimateMotion" },
    { title: "AnimateTransform", to: "/components/AnimateTransform" },
    { title: "Circle",           to: "/components/Circle" },
    { title: "ClipPath",         to: "/components/ClipPath" },
    { title: "Ellipse",          to: "/components/Ellipse" },
    { title: "ForeignObject",    to: "/components/ForeignObject" },
    { title: "Line",             to: "/components/Line" },
    { title: "LinearGradient",   to: "/components/LinearGradient" },
    { title: "Mask",             to: "/components/Mask" },
    { title: "Marker",           to: "/components/Marker" },
    { title: "MPath",            to: "/components/MPath" },
    { title: "Path",             to: "/components/Path" },
    { title: "Polygon",          to: "/components/Polygon" },
    { title: "Polyline",         to: "/components/Polyline" },
    { title: "RadialGradient",   to: "/components/RadialGradient" },
    { title: "Rect",             to: "/components/Rect" },
    { title: "Stop",             to: "/components/Stop" },
    { title: "Svg",              to: "/components/Svg" },
    { title: "Symbol",           to: "/components/Symbol" },
    { title: "Text",             to: "/components/Text" },
    { title: "TextPath",         to: "/components/TextPath" },
    { title: "TSpan",            to: "/components/TSpan" },
    { title: "Use",              to: "/components/Use" },
]
