export type { MonacoApi } from "./monacoApi"
export { monacoApi } from "./monacoApi"
export { DarkPlusMonacoTheme } from "./dark-plus-monaco-theme"
export { configureMonaco } from "./configure-monaco"
export { addShortcut } from "./add-shortcut"
