export type { CustomMonaco } from "./custom-monaco"
export { customMonaco } from "./custom-monaco"
export { DarkPlusMonacoTheme } from "./dark-plus-monaco-theme"
export { configureMonaco } from "./configure-monaco"
export { addShortcut } from "./add-shortcut"
