import dedent from "dedent"

export const DRAW_ARGS_DATA: PropData[] = [
    { name: "M", description: "moveto_absolute",            type: `[x: number, y: number]` },
    { name: "m", description: "moveto_relative",            type: `[dx: number, dy: number]` },
    { name: "L", description: "lineto_absolute",            type: `[x: number, y: number]` },
    { name: "l", description: "lineto_relative",            type: `[dx: number, dy: number]` },
    { name: "H", description: "horizontal_lineto_absolute", type: `number` },
    { name: "h", description: "horizontal_lineto_relative", type: `number` },
    { name: "V", description: "vertical_lineto_absolute",   type: `number` },
    { name: "v", description: "vertical_lineto_relative",   type: `number` },
    { name: "C", description: "curveto_absolute",           type: `[\n    x1: number, y1: number,\n    x2: number, y2: number,\n    x:  number, y:  number\n]` },
    { name: "c", description: "curveto_relative",           type: `[\n    dx1: number, dy1: number,\n    dx2: number, dy2: number,\n    dx:  number, dy:  number\n]` },
    { name: "S", description: "smooth_curveto_absolute",    type: `[\n    x2: number, y2: number,\n    x:  number, y:  number\n]` },
    { name: "s", description: "smooth_curveto_relative",    type: `[\n    dx2: number, dy2: number,\n    dx:  number, dy:  number\n]` },
    { name: "Q", description: "quadratic_bezier_curveto_absolute", type: `[\n    x1: number, y1: number,\n    x:  number, y:  number\n]` },
    { name: "q", description: "quadratic_bezier_curveto_relative", type: `[\n    dx1: number, dy1: number,\n    dx:  number, dy:  number\n]` },
    { name: "T", description: "smooth_quadratic_bezier_curveto_absolute", type: `[ x: number,  y: number]` },
    { name: "t", description: "smooth_quadratic_bezier_curveto_relative", type: `[dx: number, dy: number]` },
    { name: "A", description: "elliptical_arc_absolute", type: dedent`[
        rx: number,
        ry: number,
        angle: number,
        largeArcFlag: 0 | 1,
        sweepFlag:    0 | 1,
        x: number,
        y: number,
    ]` },
    { name: "a", description: "elliptical_arc_relative", type: dedent`[
        rx: number,
        ry: number,
        angle: number,
        largeArcFlag: 0 | 1,
        sweepFlag:    0 | 1,
        x: number,
        y: number,
    ]` },
    { name: "Z", description: "closepath", type: `null | undefined` },
    { name: "z", description: "closepath (*just lowercase*)", type: `null | undefined` },

]
